adds DSLinkWidget
DemocracyClub/dc_django_utils pull request #60
Opened 2024-01-19 15:45 UTC by awdem

This PR adds the `DSLinkWidget `which is used in filters across multiple DC projects to `dc_django_utils `so that it can be imported from the package rather than duplicated every time.

`DSLinkWidget `extends `LinkWidget ` from `django_filter `so `django_filter `must already be installed on the project to use this widget or it will throw an error on the widget's import.

Successfully tested locally but would be good to get a 2nd confirmation!

2024-01-24 17:34 UTC, symroe requested changes
Thanks Will! 

I've not thought through the implications of this at all (e.g having code that depends on something we're not installing), but I think the try/except is reasonable. 

I'd like to see something about how we might test this, or some documentation about the fact it exists. Can you add something to the project README about it?

2024-01-31 17:41 UTC, awdem commented
> Thanks Will!
> 
> I've not thought through the implications of this at all (e.g having code that depends on something we're not installing), but I think the try/except is reasonable.
> 
> I'd like to see something about how we might test this, or some documentation about the fact it exists. Can you add something to the project README about it?

I've done a bit of googling. This [stack overflow question](https://stackoverflow.com/questions/74709237/specifying-a-suggested-package-in-a-python-package) seems to reach the same conclusion to use try/except.

There is also a way of adding [optional dependencies](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies) to python packages.  If we did that, projects that use the widget would instead have to require `dc_django_utils[django_filter]` or something along those lines and projects that didn't wouldn't have to change. Not sure if that's better?

RE testing: [tox](https://tox.wiki/en/latest/) is a testing package that lets you run tests in multiple venvs with different dependencies, python versions, etc - that could be a way to test a range of ` django_filter ` versions to make sure the widget is working? (maybe a bit overkill, since this isn't a critical PR)

RE the readme: I added a very short warning, let me know if I should add more!

2024-02-01 11:53 UTC, symroe commented
Thanks Will, I think this is a good enough improvement as is, but useful to have an idea about how we might test in future.

On using tox: we do use it (or have in the past), but the problem with using it in the way you suggest is that the matrix could get _huge_. We [already test this project against](https://github.com/DemocracyClub/dc_django_utils/blob/main/.circleci/config.yml#L58-L61) various Python and Django versions. Adding Django-Filter to that would grow it by a dimension, but then what if we had another package? We'd have to test against all versions of that too. It doesn't seem very scalable!

So I suspect what will happen is that when it breaks, we'll come back to this and add a check for the supported versions. We can raise an exception then.

The next thing to do after merging this is to release the project. Let's have a chat about that. We should have documentation for it

2024-02-21 11:32 UTC, GeoWill commented
Just bumping this. It would be useful to if we're going to add filtering to https://wheredoivote.co.uk/uploads/councils/.
If I can help lmk.

2024-02-21 14:38 UTC, symroe approved these changes

2024-02-21 14:39 UTC, merged